# Generated by Django 6.0.1 on 2026-02-03 20:09

import django.db.models.deletion
from django.db import migrations, models


def seed_default_departments(apps, schema_editor):
    Office = apps.get_model("inventory", "Office")
    Department = apps.get_model("inventory", "Department")
    DepartmentPosition = apps.get_model("inventory", "DepartmentPosition")

    defaults = [
        ("Yellow", "yellow"),
        ("Blue", "blue"),
        ("Green", "green"),
        ("Purple", "purple"),
        ("Orange", "orange"),
    ]

    for office in Office.objects.all():
        for name, color in defaults:
            department, _ = Department.objects.get_or_create(
                office=office,
                name=name,
                defaults={"color": color},
            )

            existing = set(
                DepartmentPosition.objects.filter(department=department).values_list("number", flat=True)
            )
            DepartmentPosition.objects.bulk_create(
                [
                    DepartmentPosition(department=department, number=idx)
                    for idx in range(1, 11)
                    if idx not in existing
                ]
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_person_user_and_loan_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange')], max_length=20)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='inventory.office')),
            ],
            options={
                'ordering': ['office__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='inventory.department')),
            ],
            options={
                'ordering': ['department__office__name', 'department__name', 'number'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='department_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='inventory.departmentposition'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('office', 'name'), name='uniq_department_office_name'),
        ),
        migrations.AddConstraint(
            model_name='departmentposition',
            constraint=models.UniqueConstraint(fields=('department', 'number'), name='uniq_department_position'),
        ),
        migrations.RunPython(seed_default_departments, noop_reverse),
    ]
